# Generated by Django 5.1.5 on 2026-01-04 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Vehical_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='Supplier',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='Vehical',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='Route',
            new_name='route',
        ),
        migrations.AddField(
            model_name='jobs',
            name='cos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobs',
            name='profit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobs',
            name='sale',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='representative',
            name='Sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='representative',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medway.jobs')),
            ],
        ),
        migrations.CreateModel(
            name='Monthly_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=255)),
                ('sales', models.IntegerField(default=0)),
                ('Rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medway.representative')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Barcode_no', models.CharField(max_length=20)),
                ('cost', models.CharField(max_length=7)),
                ('Selling_price', models.CharField(max_length=7)),
                ('Retail_price', models.CharField(max_length=7)),
                ('Supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Medway.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Medway.jobs')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Medway.sale')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medway.product')),
                ('vehical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medway.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='Vehicle',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='Medway.vehicle'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Main_store',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Vehicals',
        ),
    ]
