# Generated by Django 5.1.5 on 2026-01-04 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0002_sale_store_vehicle_remove_products_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='is_active',
        ),
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(through='Medway.StoreProduct', to='Medway.product'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medway.store'),
        ),
    ]
