# Generated by Django 5.1.5 on 2025-03-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='product',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='quantity',
        ),
    ]
