# Generated by Django 5.1.5 on 2025-03-19 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0004_delete_main_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='existing_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='name',
        ),
        migrations.AddField(
            model_name='store',
            name='vehical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medway.vehicals'),
        ),
        migrations.AddField(
            model_name='store',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medway.existing_store'),
        ),
    ]
