# Generated by Django 5.1.5 on 2025-03-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0006_remove_store_store_storeproduct_vehical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='Name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
