# Generated by Django 5.1.5 on 2025-03-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0007_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='vehical',
        ),
    ]
