# Generated by Django 5.1.5 on 2025-03-19 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0008_remove_store_vehical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproduct',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medway.store'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='vehical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medway.vehicals'),
        ),
    ]
