# Generated by Django 5.1.5 on 2025-03-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0012_rename_route_jobs_route_jobs_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='sales',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
