# Generated by Django 5.1.5 on 2025-04-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0019_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cost_of_sales',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='expenses',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='sales',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='sale',
            field=models.IntegerField(default=0),
        ),
    ]
