# Generated by Django 5.1.5 on 2025-04-11 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0020_sale_cost_of_sales_sale_description_sale_expenses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='cost_of_sales',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='expenses',
        ),
    ]
