# Generated by Django 5.1.5 on 2025-04-28 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0023_expenses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={},
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medway.jobs'),
        ),
    ]
