# Generated by Django 5.1.5 on 2025-12-12 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0024_alter_expenses_options_remove_expenses_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='sale_reports/%Y-%m-%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Medway.sale')),
            ],
        ),
    ]
