# Generated by Django 5.1.5 on 2025-12-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0026_remove_sale_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Retail_price',
            field=models.CharField(default=200, max_length=7),
            preserve_default=False,
        ),
    ]
