# Generated by Django 5.1.5 on 2025-12-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0027_product_retail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
