# Generated by Django 5.1.5 on 2025-12-30 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0028_jobs_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sales',
        ),
        migrations.AddField(
            model_name='sale',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Medway.jobs')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Medway.sale')),
            ],
        ),
        migrations.DeleteModel(
            name='SaleReport',
        ),
    ]
