# Generated by Django 5.1.5 on 2025-12-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0029_remove_sale_sales_sale_total_sales_saleitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='Sales',
            field=models.IntegerField(default=0),
        ),
    ]
