# Generated by Django 5.1.5 on 2025-12-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0030_representative_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
