# Generated by Django 5.1.5 on 2025-12-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0032_monthly_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
