# Generated by Django 5.1.5 on 2025-12-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0033_alter_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_sales',
            name='month',
            field=models.CharField(max_length=255),
        ),
    ]
