# Generated by Django 5.1.5 on 2025-03-17 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Nic', models.CharField(max_length=12)),
                ('Phone', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Barcode_no', models.CharField(max_length=20)),
                ('Buying_price', models.CharField(max_length=7)),
                ('Selling_price', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Nic', models.CharField(max_length=12, unique=True)),
                ('Phone', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Route_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehical_type', models.CharField(max_length=500)),
                ('Vehical_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Main_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medway.products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='Supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Medway.supplier'),
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medway.drivers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medway.products')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medway.representative')),
                ('Route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medway.route')),
                ('Vehical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medway.vehicals')),
            ],
        ),
    ]
