# Generated by Django 5.1.5 on 2025-03-19 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0003_store_rename_products_product_storeproduct_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main_store',
        ),
    ]
