# Generated by Django 5.1.5 on 2025-03-19 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0005_existing_store_remove_store_name_store_vehical_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store',
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='vehical',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Medway.vehicals'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='existing_store',
        ),
    ]
