# Generated by Django 5.1.5 on 2025-03-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0009_alter_storeproduct_store_alter_storeproduct_vehical'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='Name',
            new_name='name',
        ),
    ]
