# Generated by Django 5.1.5 on 2025-03-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0010_rename_name_store_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicals',
            new_name='Vehicle',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='Vehical',
            new_name='Vehicle',
        ),
    ]
