# Generated by Django 5.1.5 on 2025-03-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0011_rename_vehicals_vehicle_rename_vehical_jobs_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='Route',
            new_name='route',
        ),
        migrations.AddField(
            model_name='jobs',
            name='sales',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
