# Generated by Django 5.1.5 on 2025-03-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0014_rename_vehical_type_vehicle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='sales',
            new_name='sale',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Buying_price',
            new_name='cost',
        ),
    ]
