# Generated by Django 5.1.5 on 2025-03-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0015_rename_sales_jobs_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='sale',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
