# Generated by Django 5.1.5 on 2025-03-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0017_alter_jobs_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='sale',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
