# Generated by Django 5.1.5 on 2025-04-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0021_remove_sale_cost_of_sales_remove_sale_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='cos',
            field=models.IntegerField(default=0),
        ),
    ]
