# Generated by Django 5.1.5 on 2025-12-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0025_salereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='description',
        ),
    ]
