# Generated by Django 5.1.5 on 2025-12-30 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medway', '0031_alter_representative_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('sales', models.IntegerField(default=0)),
                ('Rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medway.representative')),
            ],
        ),
    ]
